# Generated by Django 5.0.6 on 2024-06-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, null=False, blank=False, verbose_name="Описание")),
                ('status_choices', [('new', 'Новая'), ('in progress', 'В процессе'), ('done', 'Сделано')]),
                ('status', models.CharField(max_length=25, choices='status_choices', default='new', verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения'))]
        )]
